name: soundpool_example
description: Demonstrates how to use the soundpool plugin.
version: 0.0.1+2
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  soundpool:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - sounds/dices.m4a
    # Following sound was downloaded from http://soundbible.com/2212-Van-Sliding-Door.html
    - sounds/van-sliding-door-daniel_simon.wav
    - sounds/do-you-like-it.wav
