name: soundpool
description: A Flutter Sound Pool for playing short audio files. Sound tracks are cached in memory and played directly from cache.
version: 2.5.0
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  soundpool_platform_interface:
    git:
      url: https://github.com/simplecohesion/soundpool
      path: soundpool_platform_interface

  soundpool_web:
    git:
      url: https://github.com/simplecohesion/soundpool
      path: soundpool_web
  soundpool_macos:
    git:
      url: https://github.com/simplecohesion/soundpool
      path: soundpool_macos

flutter:
  plugin:
    platforms:
      android:
        package: pl.ukaszapps.soundpool
        pluginClass: SoundpoolPlugin
      ios:
        pluginClass: SoundpoolPlugin
      web:
        default_package: soundpool_web
      macos:
        default_package: soundpool_macos
