name: soundpool_platform_interface
description: A common platform interface for the soundpool plugin.
homepage: https://github.com/ukasz123/soundpool/tree/master/soundpool_platform_interface
version: 2.6.2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
